/*
Enum containing the names of different types of birds
 */

public enum Bird_list {
    HAWKS,EAGLES,OSPREY,EMUS,KIWIS,MOAS,OWLS,PARROTS,ROSE_RING_PARAKEET,GRAY_PARROT,SULFUR_CRESTED_COCKATOO,
    PIGEONS,DOVES,GREAT_AUK,HORNED_PUFFIN,AFRICAN_JACANA,DUCKS,SWANS, GEESE
}
